language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: gvhUNaR90RH5W8wtL5Tyq2ZB5io8Dv4VgpLcqcshacNIbVSJaAciG8vGz5Y4P65hpS24/9VW4D5Mdxr9GIRvl5uhKu6Bj2eBncB1RcaigGbpd3ZM1ewdw1fiL2gSRfoDsMXSL9LCrdh5kjrw7LojB21lsqLF9FVd8PuzefG5UCs=
  - secure: IV6JuB0waxUxgF6IUltAg/eIcNSdRVrDeRtaE8IxzKDdxm7U8h/bPnuRvYgiR8jfZx9lOfNFCpJS8u3FAUYOl2WMj8c7Kzw7vZn4jvSIswwGaxtnNvtTTLFokfYEBi7PojkQLeUDjpKG1VDZiMJ17tGwjt2vtbo+D5jlyXtOXNs=
install:
- ./gradlew clean test build publish publishBintray
